apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-service
  template:
    metadata:
      labels:
        app: config-server-service
    spec:
      containers:
        - name: config-server-service
          image: microservices-architecture-project-config-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
